Update to TileDB 2.1
TileDB-Inc/TileDB-VCF pull request #176
Opened 2020-09-29 12:48 UTC by aaronwolen

2020-09-29 13:02 UTC, Shelnutt2 commented on libtiledbvcf/cmake/Modules/FindTileDB_EP.cmake
> +      URL_HASH SHA1=1ffbad9f88e18f55a111d030aa6d3ce49bcf607f5a14d246ffc99fd5aaa820f8
This looks like a SHA256 not a SHA1

2020-09-29 14:03 UTC, aaronwolen commented on libtiledbvcf/cmake/Modules/FindTileDB_EP.cmake
> +      URL_HASH SHA1=1ffbad9f88e18f55a111d030aa6d3ce49bcf607f5a14d246ffc99fd5aaa820f8
Ha, right. I'm still in conda mode.

2020-09-30 13:27 UTC, Shelnutt2 commented
@aaronwolen can you rebase on master to get the CLI test diff output and also update to 2.1.0-rc2?

2020-10-05 17:42 UTC, Shelnutt2 requested changes

2020-10-05 17:42 UTC, Shelnutt2 commented on apis/python/tests/test_tiledbvcf.py
> +                               tiledb_config=['sm.tile_cache_size=1',
Should we change this back to 0?

2020-10-05 20:36 UTC, aaronwolen commented on apis/python/tests/test_tiledbvcf.py
> +                               tiledb_config=['sm.tile_cache_size=1',
Done.

2020-10-05 21:14 UTC, Shelnutt2 approved these changes

2020-10-05 21:33 UTC, merged