Victorgiannakouris/tiledb vcf hail
TileDB-Inc/TileDB-VCF pull request #346
Opened 2021-07-13 12:41 UTC by gsvic

2021-07-15 09:43 UTC, Shelnutt2 requested changes
Some questions and comments. Also the test dataset must be put into a versioned folder like all other test data so we know which VCF schema the data was created with and as we change overtime we can maintain tests for backwards compatibility.

2021-07-15 09:43 UTC, Shelnutt2 commented on apis/spark/src/main/resources/build-info.properties
> +[Build Metadata]
Should this be included? We probably need to put this in gitignore?

2021-07-15 09:43 UTC, Shelnutt2 commented on apis/spark/src/main/scala/TileDBVCFHailReader.scala
> +  //  val fmt = vcfReader.fmtAttributes.keySet.toArray.map{ fmtAttr =>
Should this be removed?

2021-07-15 09:43 UTC, Shelnutt2 commented on apis/spark/src/main/scala/TileDBVCFHailReader.scala
> +    //    var projection = df.groupBy("contig","posStart", "alleles")
Remove?

2021-07-15 09:43 UTC, Shelnutt2 commented on apis/spark/src/main/scala/TileDBVCFHailReader.scala
> +    val infoFields = Seq("AD", "DP", "GQ", "GT", "MIN_DP", "PL", "SB")
There can be a lot more info fields than these, we should use the API we have to list info fields.

2021-07-15 09:43 UTC, Shelnutt2 commented on apis/spark/src/main/scala/TileDBVCFHailReader.scala
> +    var projection = df
Why are all these fields hard coded?

2021-07-15 09:43 UTC, Shelnutt2 commented on apis/spark/src/main/scala/TileDBVCFHailReader.scala
> +    var columns = Seq[String]("contig", "posStart", "alleles")
Why are thee columns hard coded?

2024-06-24 10:52 UTC, gspowley commented
Closing stale PR.

2024-06-24 10:52 UTC, closed without merging