Add support for the new TileDB group API
TileDB-Inc/TileDB-VCF pull request #437
Opened 2022-05-18 20:15 UTC by gspowley

Add support for the new group API in TileDB 2.8

2022-05-18 20:18 UTC, Shelnutt2 requested changes
I think we also need to change the `open` functionality. I believe also we should add names for the different group members so in the open you can use `root_group.member("data")` etc.

2022-05-20 17:44 UTC, gspowley commented
The array `open` functionality is updated to use group member URIs.

2022-05-20 17:44 UTC, gspowley commented
The array `open` functionality is updated to use group member URIs.

2022-05-20 19:04 UTC, aaronwolen approved these changes
🚀

2022-05-23 13:16 UTC, Shelnutt2 approved these changes

2022-05-23 14:03 UTC, merged